<?php
/**
 * AddressApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Axro\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\Axro\ApiException;
use OpenAPI\Client\Axro\Configuration;
use OpenAPI\Client\Axro\FormDataProcessor;
use OpenAPI\Client\Axro\HeaderSelector;
use OpenAPI\Client\Axro\ObjectSerializer;

/**
 * AddressApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'billingGetApiV1AddressBillingGet' => [
            'application/json',
        ],
        'shippingCreateApiV1AddressShippingPost' => [
            'application/json',
        ],
        'shippingGetApiV1AddressShippingGet' => [
            'application/json',
        ],
        'shippingGetByIdApiV1AddressShippingShippingAddressIdGet' => [
            'application/json',
        ],
        'shippingUpdateApiV1AddressShippingShippingAddressIdPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation billingGetApiV1AddressBillingGet
     *
     * Get billing address
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['billingGetApiV1AddressBillingGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\AppSchemasAddressBillingAddressInfo
     */
    public function billingGetApiV1AddressBillingGet(string $contentType = self::contentTypes['billingGetApiV1AddressBillingGet'][0])
    {
        list($response) = $this->billingGetApiV1AddressBillingGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation billingGetApiV1AddressBillingGetWithHttpInfo
     *
     * Get billing address
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['billingGetApiV1AddressBillingGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\AppSchemasAddressBillingAddressInfo, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingGetApiV1AddressBillingGetWithHttpInfo(string $contentType = self::contentTypes['billingGetApiV1AddressBillingGet'][0])
    {
        $request = $this->billingGetApiV1AddressBillingGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressBillingAddressInfo',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\AppSchemasAddressBillingAddressInfo',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressBillingAddressInfo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation billingGetApiV1AddressBillingGetAsync
     *
     * Get billing address
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['billingGetApiV1AddressBillingGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function billingGetApiV1AddressBillingGetAsync(string $contentType = self::contentTypes['billingGetApiV1AddressBillingGet'][0])
    {
        return $this->billingGetApiV1AddressBillingGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation billingGetApiV1AddressBillingGetAsyncWithHttpInfo
     *
     * Get billing address
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['billingGetApiV1AddressBillingGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function billingGetApiV1AddressBillingGetAsyncWithHttpInfo(string $contentType = self::contentTypes['billingGetApiV1AddressBillingGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\AppSchemasAddressBillingAddressInfo';
        $request = $this->billingGetApiV1AddressBillingGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'billingGetApiV1AddressBillingGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['billingGetApiV1AddressBillingGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function billingGetApiV1AddressBillingGetRequest(string $contentType = self::contentTypes['billingGetApiV1AddressBillingGet'][0])
    {


        $resourcePath = '/api/v1/address/billing/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingCreateApiV1AddressShippingPost
     *
     * Create shipping address
     *
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressCreate $shippingAddressCreate shippingAddressCreate (required)
     * @param  bool|null $check If true, only checks/normalizes the address via Nominatim and does not save. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingCreateApiV1AddressShippingPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\ResponseShippingCreateApiV1AddressShippingPost|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function shippingCreateApiV1AddressShippingPost($shippingAddressCreate, $check = false, string $contentType = self::contentTypes['shippingCreateApiV1AddressShippingPost'][0])
    {
        list($response) = $this->shippingCreateApiV1AddressShippingPostWithHttpInfo($shippingAddressCreate, $check, $contentType);
        return $response;
    }

    /**
     * Operation shippingCreateApiV1AddressShippingPostWithHttpInfo
     *
     * Create shipping address
     *
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressCreate $shippingAddressCreate (required)
     * @param  bool|null $check If true, only checks/normalizes the address via Nominatim and does not save. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingCreateApiV1AddressShippingPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\ResponseShippingCreateApiV1AddressShippingPost|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingCreateApiV1AddressShippingPostWithHttpInfo($shippingAddressCreate, $check = false, string $contentType = self::contentTypes['shippingCreateApiV1AddressShippingPost'][0])
    {
        $request = $this->shippingCreateApiV1AddressShippingPostRequest($shippingAddressCreate, $check, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\ResponseShippingCreateApiV1AddressShippingPost',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\ResponseShippingCreateApiV1AddressShippingPost',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\ResponseShippingCreateApiV1AddressShippingPost',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation shippingCreateApiV1AddressShippingPostAsync
     *
     * Create shipping address
     *
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressCreate $shippingAddressCreate (required)
     * @param  bool|null $check If true, only checks/normalizes the address via Nominatim and does not save. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingCreateApiV1AddressShippingPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingCreateApiV1AddressShippingPostAsync($shippingAddressCreate, $check = false, string $contentType = self::contentTypes['shippingCreateApiV1AddressShippingPost'][0])
    {
        return $this->shippingCreateApiV1AddressShippingPostAsyncWithHttpInfo($shippingAddressCreate, $check, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingCreateApiV1AddressShippingPostAsyncWithHttpInfo
     *
     * Create shipping address
     *
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressCreate $shippingAddressCreate (required)
     * @param  bool|null $check If true, only checks/normalizes the address via Nominatim and does not save. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingCreateApiV1AddressShippingPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingCreateApiV1AddressShippingPostAsyncWithHttpInfo($shippingAddressCreate, $check = false, string $contentType = self::contentTypes['shippingCreateApiV1AddressShippingPost'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\ResponseShippingCreateApiV1AddressShippingPost';
        $request = $this->shippingCreateApiV1AddressShippingPostRequest($shippingAddressCreate, $check, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingCreateApiV1AddressShippingPost'
     *
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressCreate $shippingAddressCreate (required)
     * @param  bool|null $check If true, only checks/normalizes the address via Nominatim and does not save. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingCreateApiV1AddressShippingPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingCreateApiV1AddressShippingPostRequest($shippingAddressCreate, $check = false, string $contentType = self::contentTypes['shippingCreateApiV1AddressShippingPost'][0])
    {

        // verify the required parameter 'shippingAddressCreate' is set
        if ($shippingAddressCreate === null || (is_array($shippingAddressCreate) && count($shippingAddressCreate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingAddressCreate when calling shippingCreateApiV1AddressShippingPost'
            );
        }



        $resourcePath = '/api/v1/address/shipping/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $check,
            'check', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($shippingAddressCreate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($shippingAddressCreate));
            } else {
                $httpBody = $shippingAddressCreate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingGetApiV1AddressShippingGet
     *
     * Get shipping addresses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetApiV1AddressShippingGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo[]
     */
    public function shippingGetApiV1AddressShippingGet(string $contentType = self::contentTypes['shippingGetApiV1AddressShippingGet'][0])
    {
        list($response) = $this->shippingGetApiV1AddressShippingGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation shippingGetApiV1AddressShippingGetWithHttpInfo
     *
     * Get shipping addresses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetApiV1AddressShippingGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo[], HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingGetApiV1AddressShippingGetWithHttpInfo(string $contentType = self::contentTypes['shippingGetApiV1AddressShippingGet'][0])
    {
        $request = $this->shippingGetApiV1AddressShippingGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation shippingGetApiV1AddressShippingGetAsync
     *
     * Get shipping addresses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetApiV1AddressShippingGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingGetApiV1AddressShippingGetAsync(string $contentType = self::contentTypes['shippingGetApiV1AddressShippingGet'][0])
    {
        return $this->shippingGetApiV1AddressShippingGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingGetApiV1AddressShippingGetAsyncWithHttpInfo
     *
     * Get shipping addresses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetApiV1AddressShippingGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingGetApiV1AddressShippingGetAsyncWithHttpInfo(string $contentType = self::contentTypes['shippingGetApiV1AddressShippingGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo[]';
        $request = $this->shippingGetApiV1AddressShippingGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingGetApiV1AddressShippingGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetApiV1AddressShippingGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingGetApiV1AddressShippingGetRequest(string $contentType = self::contentTypes['shippingGetApiV1AddressShippingGet'][0])
    {


        $resourcePath = '/api/v1/address/shipping/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingGetByIdApiV1AddressShippingShippingAddressIdGet
     *
     * Get shipping address by ID
     *
     * @param  string $shippingAddressId shippingAddressId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function shippingGetByIdApiV1AddressShippingShippingAddressIdGet($shippingAddressId, string $contentType = self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'][0])
    {
        list($response) = $this->shippingGetByIdApiV1AddressShippingShippingAddressIdGetWithHttpInfo($shippingAddressId, $contentType);
        return $response;
    }

    /**
     * Operation shippingGetByIdApiV1AddressShippingShippingAddressIdGetWithHttpInfo
     *
     * Get shipping address by ID
     *
     * @param  string $shippingAddressId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingGetByIdApiV1AddressShippingShippingAddressIdGetWithHttpInfo($shippingAddressId, string $contentType = self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'][0])
    {
        $request = $this->shippingGetByIdApiV1AddressShippingShippingAddressIdGetRequest($shippingAddressId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation shippingGetByIdApiV1AddressShippingShippingAddressIdGetAsync
     *
     * Get shipping address by ID
     *
     * @param  string $shippingAddressId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingGetByIdApiV1AddressShippingShippingAddressIdGetAsync($shippingAddressId, string $contentType = self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'][0])
    {
        return $this->shippingGetByIdApiV1AddressShippingShippingAddressIdGetAsyncWithHttpInfo($shippingAddressId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingGetByIdApiV1AddressShippingShippingAddressIdGetAsyncWithHttpInfo
     *
     * Get shipping address by ID
     *
     * @param  string $shippingAddressId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingGetByIdApiV1AddressShippingShippingAddressIdGetAsyncWithHttpInfo($shippingAddressId, string $contentType = self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo';
        $request = $this->shippingGetByIdApiV1AddressShippingShippingAddressIdGetRequest($shippingAddressId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingGetByIdApiV1AddressShippingShippingAddressIdGet'
     *
     * @param  string $shippingAddressId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingGetByIdApiV1AddressShippingShippingAddressIdGetRequest($shippingAddressId, string $contentType = self::contentTypes['shippingGetByIdApiV1AddressShippingShippingAddressIdGet'][0])
    {

        // verify the required parameter 'shippingAddressId' is set
        if ($shippingAddressId === null || (is_array($shippingAddressId) && count($shippingAddressId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingAddressId when calling shippingGetByIdApiV1AddressShippingShippingAddressIdGet'
            );
        }


        $resourcePath = '/api/v1/address/shipping/{shipping_address_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($shippingAddressId !== null) {
            $resourcePath = str_replace(
                '{' . 'shipping_address_id' . '}',
                ObjectSerializer::toPathValue($shippingAddressId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingUpdateApiV1AddressShippingShippingAddressIdPut
     *
     * Update shipping address
     *
     * @param  string $shippingAddressId shippingAddressId (required)
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressUpdate $shippingAddressUpdate shippingAddressUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function shippingUpdateApiV1AddressShippingShippingAddressIdPut($shippingAddressId, $shippingAddressUpdate, string $contentType = self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'][0])
    {
        list($response) = $this->shippingUpdateApiV1AddressShippingShippingAddressIdPutWithHttpInfo($shippingAddressId, $shippingAddressUpdate, $contentType);
        return $response;
    }

    /**
     * Operation shippingUpdateApiV1AddressShippingShippingAddressIdPutWithHttpInfo
     *
     * Update shipping address
     *
     * @param  string $shippingAddressId (required)
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressUpdate $shippingAddressUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingUpdateApiV1AddressShippingShippingAddressIdPutWithHttpInfo($shippingAddressId, $shippingAddressUpdate, string $contentType = self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'][0])
    {
        $request = $this->shippingUpdateApiV1AddressShippingShippingAddressIdPutRequest($shippingAddressId, $shippingAddressUpdate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation shippingUpdateApiV1AddressShippingShippingAddressIdPutAsync
     *
     * Update shipping address
     *
     * @param  string $shippingAddressId (required)
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressUpdate $shippingAddressUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingUpdateApiV1AddressShippingShippingAddressIdPutAsync($shippingAddressId, $shippingAddressUpdate, string $contentType = self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'][0])
    {
        return $this->shippingUpdateApiV1AddressShippingShippingAddressIdPutAsyncWithHttpInfo($shippingAddressId, $shippingAddressUpdate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingUpdateApiV1AddressShippingShippingAddressIdPutAsyncWithHttpInfo
     *
     * Update shipping address
     *
     * @param  string $shippingAddressId (required)
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressUpdate $shippingAddressUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingUpdateApiV1AddressShippingShippingAddressIdPutAsyncWithHttpInfo($shippingAddressId, $shippingAddressUpdate, string $contentType = self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\AppSchemasAddressShippingAddressInfo';
        $request = $this->shippingUpdateApiV1AddressShippingShippingAddressIdPutRequest($shippingAddressId, $shippingAddressUpdate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingUpdateApiV1AddressShippingShippingAddressIdPut'
     *
     * @param  string $shippingAddressId (required)
     * @param  \OpenAPI\Client\Axro\Model\ShippingAddressUpdate $shippingAddressUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingUpdateApiV1AddressShippingShippingAddressIdPutRequest($shippingAddressId, $shippingAddressUpdate, string $contentType = self::contentTypes['shippingUpdateApiV1AddressShippingShippingAddressIdPut'][0])
    {

        // verify the required parameter 'shippingAddressId' is set
        if ($shippingAddressId === null || (is_array($shippingAddressId) && count($shippingAddressId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingAddressId when calling shippingUpdateApiV1AddressShippingShippingAddressIdPut'
            );
        }

        // verify the required parameter 'shippingAddressUpdate' is set
        if ($shippingAddressUpdate === null || (is_array($shippingAddressUpdate) && count($shippingAddressUpdate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingAddressUpdate when calling shippingUpdateApiV1AddressShippingShippingAddressIdPut'
            );
        }


        $resourcePath = '/api/v1/address/shipping/{shipping_address_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($shippingAddressId !== null) {
            $resourcePath = str_replace(
                '{' . 'shipping_address_id' . '}',
                ObjectSerializer::toPathValue($shippingAddressId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($shippingAddressUpdate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($shippingAddressUpdate));
            } else {
                $httpBody = $shippingAddressUpdate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
