<?php
/**
 * InformationApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Axro\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\Axro\ApiException;
use OpenAPI\Client\Axro\Configuration;
use OpenAPI\Client\Axro\FormDataProcessor;
use OpenAPI\Client\Axro\HeaderSelector;
use OpenAPI\Client\Axro\ObjectSerializer;

/**
 * InformationApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InformationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getOrderDetailsApiV1InformationOrderDetailOrderNumberGet' => [
            'application/json',
        ],
        'getOrderListApiV1InformationOrderListGet' => [
            'application/json',
        ],
        'getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet' => [
            'application/json',
        ],
        'getShipmentListApiV1InformationShipmentListGet' => [
            'application/json',
        ],
        'getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getOrderDetailsApiV1InformationOrderDetailOrderNumberGet
     *
     * Get order details
     *
     * @param  string $orderNumber orderNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\OrderDetailsResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getOrderDetailsApiV1InformationOrderDetailOrderNumberGet($orderNumber, string $contentType = self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'][0])
    {
        list($response) = $this->getOrderDetailsApiV1InformationOrderDetailOrderNumberGetWithHttpInfo($orderNumber, $contentType);
        return $response;
    }

    /**
     * Operation getOrderDetailsApiV1InformationOrderDetailOrderNumberGetWithHttpInfo
     *
     * Get order details
     *
     * @param  string $orderNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\OrderDetailsResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrderDetailsApiV1InformationOrderDetailOrderNumberGetWithHttpInfo($orderNumber, string $contentType = self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'][0])
    {
        $request = $this->getOrderDetailsApiV1InformationOrderDetailOrderNumberGetRequest($orderNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\OrderDetailsResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\OrderDetailsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\OrderDetailsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOrderDetailsApiV1InformationOrderDetailOrderNumberGetAsync
     *
     * Get order details
     *
     * @param  string $orderNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderDetailsApiV1InformationOrderDetailOrderNumberGetAsync($orderNumber, string $contentType = self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'][0])
    {
        return $this->getOrderDetailsApiV1InformationOrderDetailOrderNumberGetAsyncWithHttpInfo($orderNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrderDetailsApiV1InformationOrderDetailOrderNumberGetAsyncWithHttpInfo
     *
     * Get order details
     *
     * @param  string $orderNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderDetailsApiV1InformationOrderDetailOrderNumberGetAsyncWithHttpInfo($orderNumber, string $contentType = self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\OrderDetailsResponse';
        $request = $this->getOrderDetailsApiV1InformationOrderDetailOrderNumberGetRequest($orderNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'
     *
     * @param  string $orderNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOrderDetailsApiV1InformationOrderDetailOrderNumberGetRequest($orderNumber, string $contentType = self::contentTypes['getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'][0])
    {

        // verify the required parameter 'orderNumber' is set
        if ($orderNumber === null || (is_array($orderNumber) && count($orderNumber) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $orderNumber when calling getOrderDetailsApiV1InformationOrderDetailOrderNumberGet'
            );
        }


        $resourcePath = '/api/v1/information/order/detail/{order_number}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($orderNumber !== null) {
            $resourcePath = str_replace(
                '{' . 'order_number' . '}',
                ObjectSerializer::toPathValue($orderNumber),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOrderListApiV1InformationOrderListGet
     *
     * Get order list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderListApiV1InformationOrderListGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\OrderListResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getOrderListApiV1InformationOrderListGet($page = null, string $contentType = self::contentTypes['getOrderListApiV1InformationOrderListGet'][0])
    {
        list($response) = $this->getOrderListApiV1InformationOrderListGetWithHttpInfo($page, $contentType);
        return $response;
    }

    /**
     * Operation getOrderListApiV1InformationOrderListGetWithHttpInfo
     *
     * Get order list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderListApiV1InformationOrderListGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\OrderListResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrderListApiV1InformationOrderListGetWithHttpInfo($page = null, string $contentType = self::contentTypes['getOrderListApiV1InformationOrderListGet'][0])
    {
        $request = $this->getOrderListApiV1InformationOrderListGetRequest($page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\OrderListResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\OrderListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\OrderListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOrderListApiV1InformationOrderListGetAsync
     *
     * Get order list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderListApiV1InformationOrderListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderListApiV1InformationOrderListGetAsync($page = null, string $contentType = self::contentTypes['getOrderListApiV1InformationOrderListGet'][0])
    {
        return $this->getOrderListApiV1InformationOrderListGetAsyncWithHttpInfo($page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrderListApiV1InformationOrderListGetAsyncWithHttpInfo
     *
     * Get order list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderListApiV1InformationOrderListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderListApiV1InformationOrderListGetAsyncWithHttpInfo($page = null, string $contentType = self::contentTypes['getOrderListApiV1InformationOrderListGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\OrderListResponse';
        $request = $this->getOrderListApiV1InformationOrderListGetRequest($page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrderListApiV1InformationOrderListGet'
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOrderListApiV1InformationOrderListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOrderListApiV1InformationOrderListGetRequest($page = null, string $contentType = self::contentTypes['getOrderListApiV1InformationOrderListGet'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling InformationApi.getOrderListApiV1InformationOrderListGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/api/v1/information/order/list/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet
     *
     * Get shipment details
     *
     * @param  string $shipmentNumber shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\ShipmentDetailsResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet($shipmentNumber, string $contentType = self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'][0])
    {
        list($response) = $this->getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetWithHttpInfo($shipmentNumber, $contentType);
        return $response;
    }

    /**
     * Operation getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetWithHttpInfo
     *
     * Get shipment details
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\ShipmentDetailsResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetWithHttpInfo($shipmentNumber, string $contentType = self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'][0])
    {
        $request = $this->getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetRequest($shipmentNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\ShipmentDetailsResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\ShipmentDetailsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\ShipmentDetailsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetAsync
     *
     * Get shipment details
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetAsync($shipmentNumber, string $contentType = self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'][0])
    {
        return $this->getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetAsyncWithHttpInfo($shipmentNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetAsyncWithHttpInfo
     *
     * Get shipment details
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetAsyncWithHttpInfo($shipmentNumber, string $contentType = self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\ShipmentDetailsResponse';
        $request = $this->getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetRequest($shipmentNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGetRequest($shipmentNumber, string $contentType = self::contentTypes['getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'][0])
    {

        // verify the required parameter 'shipmentNumber' is set
        if ($shipmentNumber === null || (is_array($shipmentNumber) && count($shipmentNumber) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipmentNumber when calling getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet'
            );
        }


        $resourcePath = '/api/v1/information/shipment/detail/{shipment_number}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($shipmentNumber !== null) {
            $resourcePath = str_replace(
                '{' . 'shipment_number' . '}',
                ObjectSerializer::toPathValue($shipmentNumber),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getShipmentListApiV1InformationShipmentListGet
     *
     * Get shipment list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string|null $orderNumber Filter shipments by order number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentListApiV1InformationShipmentListGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\ShipmentListResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getShipmentListApiV1InformationShipmentListGet($page = null, $orderNumber = null, string $contentType = self::contentTypes['getShipmentListApiV1InformationShipmentListGet'][0])
    {
        list($response) = $this->getShipmentListApiV1InformationShipmentListGetWithHttpInfo($page, $orderNumber, $contentType);
        return $response;
    }

    /**
     * Operation getShipmentListApiV1InformationShipmentListGetWithHttpInfo
     *
     * Get shipment list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string|null $orderNumber Filter shipments by order number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentListApiV1InformationShipmentListGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\ShipmentListResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getShipmentListApiV1InformationShipmentListGetWithHttpInfo($page = null, $orderNumber = null, string $contentType = self::contentTypes['getShipmentListApiV1InformationShipmentListGet'][0])
    {
        $request = $this->getShipmentListApiV1InformationShipmentListGetRequest($page, $orderNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\ShipmentListResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\ShipmentListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\ShipmentListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getShipmentListApiV1InformationShipmentListGetAsync
     *
     * Get shipment list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string|null $orderNumber Filter shipments by order number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentListApiV1InformationShipmentListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShipmentListApiV1InformationShipmentListGetAsync($page = null, $orderNumber = null, string $contentType = self::contentTypes['getShipmentListApiV1InformationShipmentListGet'][0])
    {
        return $this->getShipmentListApiV1InformationShipmentListGetAsyncWithHttpInfo($page, $orderNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getShipmentListApiV1InformationShipmentListGetAsyncWithHttpInfo
     *
     * Get shipment list
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string|null $orderNumber Filter shipments by order number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentListApiV1InformationShipmentListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getShipmentListApiV1InformationShipmentListGetAsyncWithHttpInfo($page = null, $orderNumber = null, string $contentType = self::contentTypes['getShipmentListApiV1InformationShipmentListGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\ShipmentListResponse';
        $request = $this->getShipmentListApiV1InformationShipmentListGetRequest($page, $orderNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getShipmentListApiV1InformationShipmentListGet'
     *
     * @param  int|null $page Page number for pagination (optional)
     * @param  string|null $orderNumber Filter shipments by order number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getShipmentListApiV1InformationShipmentListGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getShipmentListApiV1InformationShipmentListGetRequest($page = null, $orderNumber = null, string $contentType = self::contentTypes['getShipmentListApiV1InformationShipmentListGet'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling InformationApi.getShipmentListApiV1InformationShipmentListGet, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/api/v1/information/shipment/list/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderNumber,
            'order_number', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet
     *
     * Get tracking history
     *
     * @param  string $shipmentNumber shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\TrackingHistoryResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet($shipmentNumber, string $contentType = self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'][0])
    {
        list($response) = $this->getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetWithHttpInfo($shipmentNumber, $contentType);
        return $response;
    }

    /**
     * Operation getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetWithHttpInfo
     *
     * Get tracking history
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\TrackingHistoryResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetWithHttpInfo($shipmentNumber, string $contentType = self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'][0])
    {
        $request = $this->getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetRequest($shipmentNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\TrackingHistoryResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\TrackingHistoryResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\TrackingHistoryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetAsync
     *
     * Get tracking history
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetAsync($shipmentNumber, string $contentType = self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'][0])
    {
        return $this->getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetAsyncWithHttpInfo($shipmentNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetAsyncWithHttpInfo
     *
     * Get tracking history
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetAsyncWithHttpInfo($shipmentNumber, string $contentType = self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\TrackingHistoryResponse';
        $request = $this->getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetRequest($shipmentNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'
     *
     * @param  string $shipmentNumber (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGetRequest($shipmentNumber, string $contentType = self::contentTypes['getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'][0])
    {

        // verify the required parameter 'shipmentNumber' is set
        if ($shipmentNumber === null || (is_array($shipmentNumber) && count($shipmentNumber) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipmentNumber when calling getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet'
            );
        }


        $resourcePath = '/api/v1/information/tracking/history/{shipment_number}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($shipmentNumber !== null) {
            $resourcePath = str_replace(
                '{' . 'shipment_number' . '}',
                ObjectSerializer::toPathValue($shipmentNumber),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
