<?php
/**
 * ProductApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Axro\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\Axro\ApiException;
use OpenAPI\Client\Axro\Configuration;
use OpenAPI\Client\Axro\FormDataProcessor;
use OpenAPI\Client\Axro\HeaderSelector;
use OpenAPI\Client\Axro\ObjectSerializer;

/**
 * ProductApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getApiV1ProductGet' => [
            'application/json',
        ],
        'getBrandsApiV1ProductBrandsGet' => [
            'application/json',
        ],
        'getCategoriesApiV1ProductCategoriesGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getApiV1ProductGet
     *
     * Get products by filter parameters
     *
     * @param  string|null $format Possible values: json or xml (BMEcat 2005 format) (optional)
     * @param  string|null $productNumber Use single or comma-separated AXRO numbers (Product Numbers) (optional)
     * @param  string|null $oem Use single or comma-separated OEM numbers (optional)
     * @param  string|null $ean Use single or comma-separated EAN numbers (optional)
     * @param  string|null $brand Use single or comma seperated brand names (can combined with category) (optional)
     * @param  string|null $category Use single or comma seperated category ids. Fetch via categories endpoint. (can combined with brand) (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $limit limit (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV1ProductGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\ProductsResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getApiV1ProductGet($format = null, $productNumber = null, $oem = null, $ean = null, $brand = null, $category = null, $page = 1, $limit = 100, string $contentType = self::contentTypes['getApiV1ProductGet'][0])
    {
        list($response) = $this->getApiV1ProductGetWithHttpInfo($format, $productNumber, $oem, $ean, $brand, $category, $page, $limit, $contentType);
        return $response;
    }

    /**
     * Operation getApiV1ProductGetWithHttpInfo
     *
     * Get products by filter parameters
     *
     * @param  string|null $format Possible values: json or xml (BMEcat 2005 format) (optional)
     * @param  string|null $productNumber Use single or comma-separated AXRO numbers (Product Numbers) (optional)
     * @param  string|null $oem Use single or comma-separated OEM numbers (optional)
     * @param  string|null $ean Use single or comma-separated EAN numbers (optional)
     * @param  string|null $brand Use single or comma seperated brand names (can combined with category) (optional)
     * @param  string|null $category Use single or comma seperated category ids. Fetch via categories endpoint. (can combined with brand) (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV1ProductGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\ProductsResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getApiV1ProductGetWithHttpInfo($format = null, $productNumber = null, $oem = null, $ean = null, $brand = null, $category = null, $page = 1, $limit = 100, string $contentType = self::contentTypes['getApiV1ProductGet'][0])
    {
        $request = $this->getApiV1ProductGetRequest($format, $productNumber, $oem, $ean, $brand, $category, $page, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\ProductsResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\ProductsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\ProductsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getApiV1ProductGetAsync
     *
     * Get products by filter parameters
     *
     * @param  string|null $format Possible values: json or xml (BMEcat 2005 format) (optional)
     * @param  string|null $productNumber Use single or comma-separated AXRO numbers (Product Numbers) (optional)
     * @param  string|null $oem Use single or comma-separated OEM numbers (optional)
     * @param  string|null $ean Use single or comma-separated EAN numbers (optional)
     * @param  string|null $brand Use single or comma seperated brand names (can combined with category) (optional)
     * @param  string|null $category Use single or comma seperated category ids. Fetch via categories endpoint. (can combined with brand) (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV1ProductGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getApiV1ProductGetAsync($format = null, $productNumber = null, $oem = null, $ean = null, $brand = null, $category = null, $page = 1, $limit = 100, string $contentType = self::contentTypes['getApiV1ProductGet'][0])
    {
        return $this->getApiV1ProductGetAsyncWithHttpInfo($format, $productNumber, $oem, $ean, $brand, $category, $page, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getApiV1ProductGetAsyncWithHttpInfo
     *
     * Get products by filter parameters
     *
     * @param  string|null $format Possible values: json or xml (BMEcat 2005 format) (optional)
     * @param  string|null $productNumber Use single or comma-separated AXRO numbers (Product Numbers) (optional)
     * @param  string|null $oem Use single or comma-separated OEM numbers (optional)
     * @param  string|null $ean Use single or comma-separated EAN numbers (optional)
     * @param  string|null $brand Use single or comma seperated brand names (can combined with category) (optional)
     * @param  string|null $category Use single or comma seperated category ids. Fetch via categories endpoint. (can combined with brand) (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV1ProductGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getApiV1ProductGetAsyncWithHttpInfo($format = null, $productNumber = null, $oem = null, $ean = null, $brand = null, $category = null, $page = 1, $limit = 100, string $contentType = self::contentTypes['getApiV1ProductGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\ProductsResponse';
        $request = $this->getApiV1ProductGetRequest($format, $productNumber, $oem, $ean, $brand, $category, $page, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getApiV1ProductGet'
     *
     * @param  string|null $format Possible values: json or xml (BMEcat 2005 format) (optional)
     * @param  string|null $productNumber Use single or comma-separated AXRO numbers (Product Numbers) (optional)
     * @param  string|null $oem Use single or comma-separated OEM numbers (optional)
     * @param  string|null $ean Use single or comma-separated EAN numbers (optional)
     * @param  string|null $brand Use single or comma seperated brand names (can combined with category) (optional)
     * @param  string|null $category Use single or comma seperated category ids. Fetch via categories endpoint. (can combined with brand) (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV1ProductGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getApiV1ProductGetRequest($format = null, $productNumber = null, $oem = null, $ean = null, $brand = null, $category = null, $page = 1, $limit = 100, string $contentType = self::contentTypes['getApiV1ProductGet'][0])
    {










        $resourcePath = '/api/v1/product/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $format,
            'format', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $productNumber,
            'product_number', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $oem,
            'oem', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ean,
            'ean', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $brand,
            'brand', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $category,
            'category', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBrandsApiV1ProductBrandsGet
     *
     * Get all available brands
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandsApiV1ProductBrandsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\BrandsResponse
     */
    public function getBrandsApiV1ProductBrandsGet(string $contentType = self::contentTypes['getBrandsApiV1ProductBrandsGet'][0])
    {
        list($response) = $this->getBrandsApiV1ProductBrandsGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getBrandsApiV1ProductBrandsGetWithHttpInfo
     *
     * Get all available brands
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandsApiV1ProductBrandsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\BrandsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBrandsApiV1ProductBrandsGetWithHttpInfo(string $contentType = self::contentTypes['getBrandsApiV1ProductBrandsGet'][0])
    {
        $request = $this->getBrandsApiV1ProductBrandsGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\BrandsResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\BrandsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\BrandsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getBrandsApiV1ProductBrandsGetAsync
     *
     * Get all available brands
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandsApiV1ProductBrandsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBrandsApiV1ProductBrandsGetAsync(string $contentType = self::contentTypes['getBrandsApiV1ProductBrandsGet'][0])
    {
        return $this->getBrandsApiV1ProductBrandsGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBrandsApiV1ProductBrandsGetAsyncWithHttpInfo
     *
     * Get all available brands
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandsApiV1ProductBrandsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBrandsApiV1ProductBrandsGetAsyncWithHttpInfo(string $contentType = self::contentTypes['getBrandsApiV1ProductBrandsGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\BrandsResponse';
        $request = $this->getBrandsApiV1ProductBrandsGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBrandsApiV1ProductBrandsGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandsApiV1ProductBrandsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBrandsApiV1ProductBrandsGetRequest(string $contentType = self::contentTypes['getBrandsApiV1ProductBrandsGet'][0])
    {


        $resourcePath = '/api/v1/product/brands/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCategoriesApiV1ProductCategoriesGet
     *
     * Get all available categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCategoriesApiV1ProductCategoriesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\CategoryResponseSchema[]
     */
    public function getCategoriesApiV1ProductCategoriesGet(string $contentType = self::contentTypes['getCategoriesApiV1ProductCategoriesGet'][0])
    {
        list($response) = $this->getCategoriesApiV1ProductCategoriesGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getCategoriesApiV1ProductCategoriesGetWithHttpInfo
     *
     * Get all available categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCategoriesApiV1ProductCategoriesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\CategoryResponseSchema[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getCategoriesApiV1ProductCategoriesGetWithHttpInfo(string $contentType = self::contentTypes['getCategoriesApiV1ProductCategoriesGet'][0])
    {
        $request = $this->getCategoriesApiV1ProductCategoriesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\CategoryResponseSchema[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\CategoryResponseSchema[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\CategoryResponseSchema[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCategoriesApiV1ProductCategoriesGetAsync
     *
     * Get all available categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCategoriesApiV1ProductCategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCategoriesApiV1ProductCategoriesGetAsync(string $contentType = self::contentTypes['getCategoriesApiV1ProductCategoriesGet'][0])
    {
        return $this->getCategoriesApiV1ProductCategoriesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCategoriesApiV1ProductCategoriesGetAsyncWithHttpInfo
     *
     * Get all available categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCategoriesApiV1ProductCategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCategoriesApiV1ProductCategoriesGetAsyncWithHttpInfo(string $contentType = self::contentTypes['getCategoriesApiV1ProductCategoriesGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\CategoryResponseSchema[]';
        $request = $this->getCategoriesApiV1ProductCategoriesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCategoriesApiV1ProductCategoriesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCategoriesApiV1ProductCategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCategoriesApiV1ProductCategoriesGetRequest(string $contentType = self::contentTypes['getCategoriesApiV1ProductCategoriesGet'][0])
    {


        $resourcePath = '/api/v1/product/categories/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
