<?php
/**
 * WebhookApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Axro\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\Axro\ApiException;
use OpenAPI\Client\Axro\Configuration;
use OpenAPI\Client\Axro\FormDataProcessor;
use OpenAPI\Client\Axro\HeaderSelector;
use OpenAPI\Client\Axro\ObjectSerializer;

/**
 * WebhookApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteSubscriptionApiV1WebhookSubscriptionDelete' => [
            'application/json',
        ],
        'getSubscriptionApiV1WebhookSubscriptionGet' => [
            'application/json',
        ],
        'subscribeApiV1WebhookSubscribePost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteSubscriptionApiV1WebhookSubscriptionDelete
     *
     * Delete webhook subscription
     *
     * @param  string|null $customerNumber customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteSubscriptionApiV1WebhookSubscriptionDelete($customerNumber = null, string $contentType = self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'][0])
    {
        $this->deleteSubscriptionApiV1WebhookSubscriptionDeleteWithHttpInfo($customerNumber, $contentType);
    }

    /**
     * Operation deleteSubscriptionApiV1WebhookSubscriptionDeleteWithHttpInfo
     *
     * Delete webhook subscription
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSubscriptionApiV1WebhookSubscriptionDeleteWithHttpInfo($customerNumber = null, string $contentType = self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'][0])
    {
        $request = $this->deleteSubscriptionApiV1WebhookSubscriptionDeleteRequest($customerNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteSubscriptionApiV1WebhookSubscriptionDeleteAsync
     *
     * Delete webhook subscription
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSubscriptionApiV1WebhookSubscriptionDeleteAsync($customerNumber = null, string $contentType = self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'][0])
    {
        return $this->deleteSubscriptionApiV1WebhookSubscriptionDeleteAsyncWithHttpInfo($customerNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSubscriptionApiV1WebhookSubscriptionDeleteAsyncWithHttpInfo
     *
     * Delete webhook subscription
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSubscriptionApiV1WebhookSubscriptionDeleteAsyncWithHttpInfo($customerNumber = null, string $contentType = self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'][0])
    {
        $returnType = '';
        $request = $this->deleteSubscriptionApiV1WebhookSubscriptionDeleteRequest($customerNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSubscriptionApiV1WebhookSubscriptionDelete'
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteSubscriptionApiV1WebhookSubscriptionDeleteRequest($customerNumber = null, string $contentType = self::contentTypes['deleteSubscriptionApiV1WebhookSubscriptionDelete'][0])
    {



        $resourcePath = '/api/v1/webhook/subscription/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customerNumber,
            'customer_number', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSubscriptionApiV1WebhookSubscriptionGet
     *
     * Get current webhook subscription
     *
     * @param  string|null $customerNumber customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\SubscriptionResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function getSubscriptionApiV1WebhookSubscriptionGet($customerNumber = null, string $contentType = self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'][0])
    {
        list($response) = $this->getSubscriptionApiV1WebhookSubscriptionGetWithHttpInfo($customerNumber, $contentType);
        return $response;
    }

    /**
     * Operation getSubscriptionApiV1WebhookSubscriptionGetWithHttpInfo
     *
     * Get current webhook subscription
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\SubscriptionResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSubscriptionApiV1WebhookSubscriptionGetWithHttpInfo($customerNumber = null, string $contentType = self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'][0])
    {
        $request = $this->getSubscriptionApiV1WebhookSubscriptionGetRequest($customerNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\SubscriptionResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\SubscriptionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\SubscriptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getSubscriptionApiV1WebhookSubscriptionGetAsync
     *
     * Get current webhook subscription
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubscriptionApiV1WebhookSubscriptionGetAsync($customerNumber = null, string $contentType = self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'][0])
    {
        return $this->getSubscriptionApiV1WebhookSubscriptionGetAsyncWithHttpInfo($customerNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSubscriptionApiV1WebhookSubscriptionGetAsyncWithHttpInfo
     *
     * Get current webhook subscription
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubscriptionApiV1WebhookSubscriptionGetAsyncWithHttpInfo($customerNumber = null, string $contentType = self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\SubscriptionResponse';
        $request = $this->getSubscriptionApiV1WebhookSubscriptionGetRequest($customerNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSubscriptionApiV1WebhookSubscriptionGet'
     *
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSubscriptionApiV1WebhookSubscriptionGetRequest($customerNumber = null, string $contentType = self::contentTypes['getSubscriptionApiV1WebhookSubscriptionGet'][0])
    {



        $resourcePath = '/api/v1/webhook/subscription/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customerNumber,
            'customer_number', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation subscribeApiV1WebhookSubscribePost
     *
     * Create or update webhook subscription
     *
     * @param  \OpenAPI\Client\Axro\Model\SubscribeRequest $subscribeRequest subscribeRequest (required)
     * @param  string|null $customerNumber customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['subscribeApiV1WebhookSubscribePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Axro\Model\SubscriptionResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError
     */
    public function subscribeApiV1WebhookSubscribePost($subscribeRequest, $customerNumber = null, string $contentType = self::contentTypes['subscribeApiV1WebhookSubscribePost'][0])
    {
        list($response) = $this->subscribeApiV1WebhookSubscribePostWithHttpInfo($subscribeRequest, $customerNumber, $contentType);
        return $response;
    }

    /**
     * Operation subscribeApiV1WebhookSubscribePostWithHttpInfo
     *
     * Create or update webhook subscription
     *
     * @param  \OpenAPI\Client\Axro\Model\SubscribeRequest $subscribeRequest (required)
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['subscribeApiV1WebhookSubscribePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Axro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Axro\Model\SubscriptionResponse|\OpenAPI\Client\Axro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function subscribeApiV1WebhookSubscribePostWithHttpInfo($subscribeRequest, $customerNumber = null, string $contentType = self::contentTypes['subscribeApiV1WebhookSubscribePost'][0])
    {
        $request = $this->subscribeApiV1WebhookSubscribePostRequest($subscribeRequest, $customerNumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\SubscriptionResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Axro\Model\SubscriptionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\SubscriptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Axro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation subscribeApiV1WebhookSubscribePostAsync
     *
     * Create or update webhook subscription
     *
     * @param  \OpenAPI\Client\Axro\Model\SubscribeRequest $subscribeRequest (required)
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['subscribeApiV1WebhookSubscribePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function subscribeApiV1WebhookSubscribePostAsync($subscribeRequest, $customerNumber = null, string $contentType = self::contentTypes['subscribeApiV1WebhookSubscribePost'][0])
    {
        return $this->subscribeApiV1WebhookSubscribePostAsyncWithHttpInfo($subscribeRequest, $customerNumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation subscribeApiV1WebhookSubscribePostAsyncWithHttpInfo
     *
     * Create or update webhook subscription
     *
     * @param  \OpenAPI\Client\Axro\Model\SubscribeRequest $subscribeRequest (required)
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['subscribeApiV1WebhookSubscribePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function subscribeApiV1WebhookSubscribePostAsyncWithHttpInfo($subscribeRequest, $customerNumber = null, string $contentType = self::contentTypes['subscribeApiV1WebhookSubscribePost'][0])
    {
        $returnType = '\OpenAPI\Client\Axro\Model\SubscriptionResponse';
        $request = $this->subscribeApiV1WebhookSubscribePostRequest($subscribeRequest, $customerNumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'subscribeApiV1WebhookSubscribePost'
     *
     * @param  \OpenAPI\Client\Axro\Model\SubscribeRequest $subscribeRequest (required)
     * @param  string|null $customerNumber (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['subscribeApiV1WebhookSubscribePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function subscribeApiV1WebhookSubscribePostRequest($subscribeRequest, $customerNumber = null, string $contentType = self::contentTypes['subscribeApiV1WebhookSubscribePost'][0])
    {

        // verify the required parameter 'subscribeRequest' is set
        if ($subscribeRequest === null || (is_array($subscribeRequest) && count($subscribeRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $subscribeRequest when calling subscribeApiV1WebhookSubscribePost'
            );
        }



        $resourcePath = '/api/v1/webhook/subscribe/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $customerNumber,
            'customer_number', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($subscribeRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($subscribeRequest));
            } else {
                $httpBody = $subscribeRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
