<?php
/**
 * OrderInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Axro\Model;

use \ArrayAccess;
use \OpenAPI\Client\Axro\ObjectSerializer;

/**
 * OrderInfo Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'shippingAddress' => '\OpenAPI\Client\Axro\Model\AppSchemasOrderShippingAddressInfo',
        'billingAddress' => '\OpenAPI\Client\Axro\Model\AppSchemasOrderBillingAddressInfo',
        'cart' => '\OpenAPI\Client\Axro\Model\CartItemInfo[]',
        'toll' => 'int',
        'freightCosts' => 'int',
        'grandTotal' => 'int',
        'customReference' => 'string',
        'additionalInformation' => 'string',
        'orderPlaced' => 'bool',
        'placeOrderUrl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'shippingAddress' => null,
        'billingAddress' => null,
        'cart' => null,
        'toll' => null,
        'freightCosts' => null,
        'grandTotal' => null,
        'customReference' => null,
        'additionalInformation' => null,
        'orderPlaced' => null,
        'placeOrderUrl' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'shippingAddress' => false,
        'billingAddress' => false,
        'cart' => false,
        'toll' => false,
        'freightCosts' => false,
        'grandTotal' => false,
        'customReference' => true,
        'additionalInformation' => true,
        'orderPlaced' => false,
        'placeOrderUrl' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shippingAddress' => 'shipping_address',
        'billingAddress' => 'billing_address',
        'cart' => 'cart',
        'toll' => 'toll',
        'freightCosts' => 'freight_costs',
        'grandTotal' => 'grand_total',
        'customReference' => 'custom_reference',
        'additionalInformation' => 'additional_information',
        'orderPlaced' => 'order_placed',
        'placeOrderUrl' => 'place_order_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shippingAddress' => 'setShippingAddress',
        'billingAddress' => 'setBillingAddress',
        'cart' => 'setCart',
        'toll' => 'setToll',
        'freightCosts' => 'setFreightCosts',
        'grandTotal' => 'setGrandTotal',
        'customReference' => 'setCustomReference',
        'additionalInformation' => 'setAdditionalInformation',
        'orderPlaced' => 'setOrderPlaced',
        'placeOrderUrl' => 'setPlaceOrderUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shippingAddress' => 'getShippingAddress',
        'billingAddress' => 'getBillingAddress',
        'cart' => 'getCart',
        'toll' => 'getToll',
        'freightCosts' => 'getFreightCosts',
        'grandTotal' => 'getGrandTotal',
        'customReference' => 'getCustomReference',
        'additionalInformation' => 'getAdditionalInformation',
        'orderPlaced' => 'getOrderPlaced',
        'placeOrderUrl' => 'getPlaceOrderUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shippingAddress', $data ?? [], null);
        $this->setIfExists('billingAddress', $data ?? [], null);
        $this->setIfExists('cart', $data ?? [], null);
        $this->setIfExists('toll', $data ?? [], null);
        $this->setIfExists('freightCosts', $data ?? [], null);
        $this->setIfExists('grandTotal', $data ?? [], null);
        $this->setIfExists('customReference', $data ?? [], null);
        $this->setIfExists('additionalInformation', $data ?? [], null);
        $this->setIfExists('orderPlaced', $data ?? [], false);
        $this->setIfExists('placeOrderUrl', $data ?? [], '/api/v1/order/?place=1');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shippingAddress'] === null) {
            $invalidProperties[] = "'shippingAddress' can't be null";
        }
        if ($this->container['billingAddress'] === null) {
            $invalidProperties[] = "'billingAddress' can't be null";
        }
        if ($this->container['cart'] === null) {
            $invalidProperties[] = "'cart' can't be null";
        }
        if ($this->container['toll'] === null) {
            $invalidProperties[] = "'toll' can't be null";
        }
        if ($this->container['freightCosts'] === null) {
            $invalidProperties[] = "'freightCosts' can't be null";
        }
        if ($this->container['grandTotal'] === null) {
            $invalidProperties[] = "'grandTotal' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shippingAddress
     *
     * @return \OpenAPI\Client\Axro\Model\AppSchemasOrderShippingAddressInfo
     */
    public function getShippingAddress()
    {
        return $this->container['shippingAddress'];
    }

    /**
     * Sets shippingAddress
     *
     * @param \OpenAPI\Client\Axro\Model\AppSchemasOrderShippingAddressInfo $shippingAddress shippingAddress
     *
     * @return self
     */
    public function setShippingAddress($shippingAddress)
    {
        if (is_null($shippingAddress)) {
            throw new \InvalidArgumentException('non-nullable shippingAddress cannot be null');
        }
        $this->container['shippingAddress'] = $shippingAddress;

        return $this;
    }

    /**
     * Gets billingAddress
     *
     * @return \OpenAPI\Client\Axro\Model\AppSchemasOrderBillingAddressInfo
     */
    public function getBillingAddress()
    {
        return $this->container['billingAddress'];
    }

    /**
     * Sets billingAddress
     *
     * @param \OpenAPI\Client\Axro\Model\AppSchemasOrderBillingAddressInfo $billingAddress billingAddress
     *
     * @return self
     */
    public function setBillingAddress($billingAddress)
    {
        if (is_null($billingAddress)) {
            throw new \InvalidArgumentException('non-nullable billingAddress cannot be null');
        }
        $this->container['billingAddress'] = $billingAddress;

        return $this;
    }

    /**
     * Gets cart
     *
     * @return \OpenAPI\Client\Axro\Model\CartItemInfo[]
     */
    public function getCart()
    {
        return $this->container['cart'];
    }

    /**
     * Sets cart
     *
     * @param \OpenAPI\Client\Axro\Model\CartItemInfo[] $cart cart
     *
     * @return self
     */
    public function setCart($cart)
    {
        if (is_null($cart)) {
            throw new \InvalidArgumentException('non-nullable cart cannot be null');
        }
        $this->container['cart'] = $cart;

        return $this;
    }

    /**
     * Gets toll
     *
     * @return int
     */
    public function getToll()
    {
        return $this->container['toll'];
    }

    /**
     * Sets toll
     *
     * @param int $toll toll
     *
     * @return self
     */
    public function setToll($toll)
    {
        if (is_null($toll)) {
            throw new \InvalidArgumentException('non-nullable toll cannot be null');
        }
        $this->container['toll'] = $toll;

        return $this;
    }

    /**
     * Gets freightCosts
     *
     * @return int
     */
    public function getFreightCosts()
    {
        return $this->container['freightCosts'];
    }

    /**
     * Sets freightCosts
     *
     * @param int $freightCosts freightCosts
     *
     * @return self
     */
    public function setFreightCosts($freightCosts)
    {
        if (is_null($freightCosts)) {
            throw new \InvalidArgumentException('non-nullable freightCosts cannot be null');
        }
        $this->container['freightCosts'] = $freightCosts;

        return $this;
    }

    /**
     * Gets grandTotal
     *
     * @return int
     */
    public function getGrandTotal()
    {
        return $this->container['grandTotal'];
    }

    /**
     * Sets grandTotal
     *
     * @param int $grandTotal grandTotal
     *
     * @return self
     */
    public function setGrandTotal($grandTotal)
    {
        if (is_null($grandTotal)) {
            throw new \InvalidArgumentException('non-nullable grandTotal cannot be null');
        }
        $this->container['grandTotal'] = $grandTotal;

        return $this;
    }

    /**
     * Gets customReference
     *
     * @return string|null
     */
    public function getCustomReference()
    {
        return $this->container['customReference'];
    }

    /**
     * Sets customReference
     *
     * @param string|null $customReference customReference
     *
     * @return self
     */
    public function setCustomReference($customReference)
    {
        if (is_null($customReference)) {
            array_push($this->openAPINullablesSetToNull, 'customReference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customReference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customReference'] = $customReference;

        return $this;
    }

    /**
     * Gets additionalInformation
     *
     * @return string|null
     */
    public function getAdditionalInformation()
    {
        return $this->container['additionalInformation'];
    }

    /**
     * Sets additionalInformation
     *
     * @param string|null $additionalInformation additionalInformation
     *
     * @return self
     */
    public function setAdditionalInformation($additionalInformation)
    {
        if (is_null($additionalInformation)) {
            array_push($this->openAPINullablesSetToNull, 'additionalInformation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('additionalInformation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['additionalInformation'] = $additionalInformation;

        return $this;
    }

    /**
     * Gets orderPlaced
     *
     * @return bool|null
     */
    public function getOrderPlaced()
    {
        return $this->container['orderPlaced'];
    }

    /**
     * Sets orderPlaced
     *
     * @param bool|null $orderPlaced orderPlaced
     *
     * @return self
     */
    public function setOrderPlaced($orderPlaced)
    {
        if (is_null($orderPlaced)) {
            throw new \InvalidArgumentException('non-nullable orderPlaced cannot be null');
        }
        $this->container['orderPlaced'] = $orderPlaced;

        return $this;
    }

    /**
     * Gets placeOrderUrl
     *
     * @return string|null
     */
    public function getPlaceOrderUrl()
    {
        return $this->container['placeOrderUrl'];
    }

    /**
     * Sets placeOrderUrl
     *
     * @param string|null $placeOrderUrl placeOrderUrl
     *
     * @return self
     */
    public function setPlaceOrderUrl($placeOrderUrl)
    {
        if (is_null($placeOrderUrl)) {
            throw new \InvalidArgumentException('non-nullable placeOrderUrl cannot be null');
        }
        $this->container['placeOrderUrl'] = $placeOrderUrl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


