<?php
/**
 * OrderInfoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Axro\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderInfoTest Class Doc Comment
 *
 * @category    Class
 * @description OrderInfo
 * @package     OpenAPI\Client\Axro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderInfo"
     */
    public function testOrderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippingAddress"
     */
    public function testPropertyShippingAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cart"
     */
    public function testPropertyCart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "toll"
     */
    public function testPropertyToll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "freightCosts"
     */
    public function testPropertyFreightCosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "grandTotal"
     */
    public function testPropertyGrandTotal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customReference"
     */
    public function testPropertyCustomReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalInformation"
     */
    public function testPropertyAdditionalInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "orderPlaced"
     */
    public function testPropertyOrderPlaced()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "placeOrderUrl"
     */
    public function testPropertyPlaceOrderUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
