<?php
/**
 * ShipmentDetailMessageTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Axro\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentDetailMessageTest Class Doc Comment
 *
 * @category    Class
 * @description Shipment detail message from the issues service.
 * @package     OpenAPI\Client\Axro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentDetailMessageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentDetailMessage"
     */
    public function testShipmentDetailMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "orderNumbers"
     */
    public function testPropertyOrderNumbers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invoiceNumber"
     */
    public function testPropertyInvoiceNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipmentNumber"
     */
    public function testPropertyShipmentNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippingDate"
     */
    public function testPropertyShippingDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
