<?php
/**
 * InformationApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Axro\Test\Api;

use \OpenAPI\Client\Axro\Configuration;
use \OpenAPI\Client\Axro\ApiException;
use \OpenAPI\Client\Axro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InformationApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InformationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getOrderDetailsApiV1InformationOrderDetailOrderNumberGet
     *
     * Get order details.
     *
     */
    public function testGetOrderDetailsApiV1InformationOrderDetailOrderNumberGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderListApiV1InformationOrderListGet
     *
     * Get order list.
     *
     */
    public function testGetOrderListApiV1InformationOrderListGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet
     *
     * Get shipment details.
     *
     */
    public function testGetShipmentDetailsApiV1InformationShipmentDetailShipmentNumberGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipmentListApiV1InformationShipmentListGet
     *
     * Get shipment list.
     *
     */
    public function testGetShipmentListApiV1InformationShipmentListGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet
     *
     * Get tracking history.
     *
     */
    public function testGetTrackingHistoryApiV1InformationTrackingHistoryShipmentNumberGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
