<?php
/**
 * WebhookApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AXRO Sales API
 *
 * The AXRO Sales API provides programmatic access to product information, pricing, inventory, orders and addresses | <a href='/documentation/'>Documentation</a>
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Axro\Test\Api;

use \OpenAPI\Client\Axro\Configuration;
use \OpenAPI\Client\Axro\ApiException;
use \OpenAPI\Client\Axro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhookApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Axro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteSubscriptionApiV1WebhookSubscriptionDelete
     *
     * Delete webhook subscription.
     *
     */
    public function testDeleteSubscriptionApiV1WebhookSubscriptionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubscriptionApiV1WebhookSubscriptionGet
     *
     * Get current webhook subscription.
     *
     */
    public function testGetSubscriptionApiV1WebhookSubscriptionGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for subscribeApiV1WebhookSubscribePost
     *
     * Create or update webhook subscription.
     *
     */
    public function testSubscribeApiV1WebhookSubscribePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
